name: Feature request
description: Suggest an idea for Notepad++
title: "[Feature request] <title>"
#labels: ["feature"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you request.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description of the Issue
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like.
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Debug Information
    description: |
      In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar).
      In the menu that drops down, choose "Debug Info...".
      A dialog will open detailing specifics about your Notepad++ version, plugins, etc.
      CLICK ON THE BUTTON "Copy debug info into clipboard".
      Do a PASTE HERE
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you want!

      Notepad++ relies on the Lexilla and Scintilla libraries.
      For more details, visit https://github.com/ScintillaOrg/lexilla and https://sourceforge.net/p/scintilla.
      If you have specific language feature requests, consider using the reference program SciTE to verify whether the desired feature is supported.
      You can download SciTE from here https://www.scintilla.org/SciTEDownload.html.

      If you have any questions about Notepad++ usage, explore the community forum https://community.notepad-plus-plus.org/category/7/faq.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
